export const photos = [
  {
    id: 1,
    group: "coin",
    src: "assets/Argonath-A.jpg",
    title: "Software Factory Logo",
    description: "Brass 40mm round coin with",
  },
  {
    id: 2,
    group: "coin",
    src: "assets/Argonath-B.jpg",
    title: "Argonath Logo",
    description: "Brass 40mm round coin with custom logo",
  },
  {
    id: 3,
    group: "coin",
    src: "assets/StarWarsCoin-A.jpg",
    title: "Darth Vader with StarWars",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 4,
    group: "coin",
    src: "assets/StarWarsCoin-B.jpg",
    title: "StarWars Aztec Calendar",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 5,
    group: "coin",
    src: "assets/Hex-Coin-A.jpg",
    title: "StarWars Aztec Calendar",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 6,
    group: "coin",
    src: "assets/Hex-Coin-B.jpg",
    title: "StarWars Aztec Calendar",
    description:
      "Brass Diameter: 26.2 mm thickness: 1.5 mm Hexagon coin with custom design",
  },
  {
    id: 7,
    group: "coin",
    src: "assets/coin-round-a.jpg",
    title: "StarWars Aztec Calendar",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 8,
    group: "coin",
    src: "assets/coin-round-b.jpg",
    title: "StarWars Aztec Calendar",
    description:
      "Brass Diameter: 26.2 mm thickness: 1.5 mm Hexagon coin with custom design",
  },
  {
    id: 9,
    group: "coin",
    src: "assets/firewire-coin.jpg",
    title: "FireWire Coin",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 10,
    group: "coin",
    src: "assets/titans-gold-coin.jpg",
    title: "Titan in Gold coin",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 11,
    group: "coin",
    src: "assets/titan-silver-coin.jpg",
    title: "Titan in Silver coin",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 12,
    group: "coin",
    src: "assets/gillman-coin.jpg",
    title: "Gillman coin",
    description: "Brass 40mm round coin with custom design",
  },
  {
    id: 13,
    group: "coin",
    src: "assets/dont stop belivin-coin.jpg",
    title: "Don't Stop Belivin' coin",
    description: "Brass 40mm round coin with custom design (English is hard)",
  },
  {
    id: 14,
    group: "jewelry",
    src: "assets/evilope-jewlrey.jpg",
    title: "Envelop necklace",
    description: "Envelop with custom design outside",
  },
  {
    id: 15,
    group: "jewelry",
    src: "assets/internal-j.jpg",
    title: "Envelop necklace",
    description: "Envelop letter with custom design",
  },
  {
    id: 16,
    group: "jewelry",
    src: "assets/internal-2-j.jpg",
    title: "Envelop necklace",
    description: "Envelop letter with custom design",
  },
  {
    id: 17,
    group: "jewelry",
    src: "assets/ring-j.jpg",
    title: "Envelop necklace",
    description: "Envelop letter with custom design",
  },
  {
    id: 18,
    group: "drinkware",
    src: "assets/thermas-small-drink.jpg",
    title: "Envelop necklace",
    description: "Small Drinkware with custom design",
  },
  {
    id: 19,
    group: "drinkware",
    src: "assets/thermas-large-drink.jpg",
    title: "Envelop necklace",
    description: "Large Drinkware with custom design",
  },
  {
    id: 20,
    group: "drinkware",
    src: "assets/togehter.jpg",
    title: "Envelop necklace",
    description: "Several Drinkwares with custom design",
  },
  {
    id: 21,
    group: "drinkware",
    src: "assets/D-CW3.jpg",
    title: "Drinkware",
    description: "Drinkwares with custom design",
  },
  {
    id: 22,
    group: "utility",
    src: "assets/U-firewire-2.jpg",
    title: "Custom Pen",
    description: "Pen with custom design",
  },
  {
    id: 23,
    group: "drinkware",
    src: "assets/D-heavy.jpg",
    title: "Envelop necklace",
    description: "Drinkwares with custom design",
  },
  {
    id: 24,
    group: "drinkware",
    src: "assets/D-Johnny5.jpg",
    title: "80s drink heroes",
    description: "Drinkwares with custom design",
  },
  {
    id: 25,
    group: "drinkware",
    src: "assets/D-poem.jpg",
    title: "Poetry Mug",
    description: "Drinkwares with custom design",
  },
  {
    id: 26,
    group: "drinkware",
    src: "assets/D-sailormoon.jpg",
    title: "Sailor Moon mug",
    description: "Drinkwares with custom design",
  },
  {
    id: 27,
    group: "drinkware",
    src: "assets/D-SWF_mug.jpg",
    title: "Company Mug",
    description: "Drinkwares with custom design",
  },
  {
    id: 28,
    group: "utility",
    src: "assets/U-dumpsterfiretech-pen.jpg",
    title: "Company Pen",
    description: "Pen with custom design",
  },
  {
    id: 29,
    group: "utility",
    src: "assets/U-firewire.jpg",
    title: "Firewire Pen",
    description: "Pen with custom design",
  },
  {
    id: 29,
    group: "utility",
    src: "assets/U-retirement.jpg",
    title: "Fun Retirement Pen",
    description: "Pen with custom design",
  },
  // Add more photos here...
];
